development:
  adapter: postgresql
  encoding: unicode
  database: dns_development
  host : <%= ENV['DB_HOST'] || db_simple_dns %>
  password: <%= ENV['DB_USERNAME'] %>
  user: <%= ENV['DB_PASSWORD'] %>